name: tests_normalized_parallel
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup python
      run: |
        pip3 install -r requirements.txt
    - name: docker
      run: |
        git submodule init
        git submodule update
        docker-compose up -d --build
        docker ps -a
        sleep 20
        sh load_tweets_parallel.sh
        docker-compose exec -T pg_normalized ./check_answers.sh

